spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: samurai
    password: password

    jpa:
      properties:
        hibernate:
          default_schema: public

  liquibase:
    change-log: db/changelog/master.yaml